services:
  mtprotoproxy:
    build: .
    restart: unless-stopped
    network_mode: "host"
    volumes:
        - ./config.py:$HOME/mtprotoproxy/config.py
        - ./mtprotoproxy.py:$HOME/mtprotoproxy/mtprotoproxy.py
        - /etc/localtime:/etc/localtime:ro
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "10m"
#    mem_limit: 1024m
